CREATE DATABASE DB_REIS
use DB_REIS

-- DECLARANDO VARIÁVEIS EM BANCO DE DADOS
CREATE TABLE [Aluno]
(Matricula Int NOT NULL Identity(1,1) --Contador automático
,NomeAluno Varchar(100) NOT NULL
,CPF CHAR(11) NOT NULL
,DataNcto SMALLDATETIME NOT NULL
,Mensalidade NUMERIC(6,2) NOT NULL
,Turma char(10) NOT NULL
)

--MANIPULAÇÃO DE DADOS
--Inserção de dados
INSERT ALUNO VALUES ('José da Silva','12345678900','19911121', 1000,'ADS3')
INSERT ALUNO VALUES ('Maria da Silva', '12345678911','20000317',1000, 'ADS1')
INSERT ALUNO VALUES ('Ana da Silva', '12345678922','20000317', 1000,'ADS3')
select * from Aluno
/* CRIAÇÃO DE VARIÁVEIS LOCAIS */
DECLARE @TOTAL INT --NÚMERO DE ALUNOS
DECLARE @VALOR NUMERIC(6,2) --VALOR TOTAL MENSALIDADE
DECLARE @VALOR_TURMA NUMERIC(6,2) --VALOR TOTAL MENSALIDADE POR TURMA
DECLARE @TURMA CHAR(5)
DECLARE @msg varchar(100)
/* DEFINE O VALOR DE CADA VARIÁVEL */

SET @TURMA = 'ADS3'
SET @TOTAL = (SELECT COUNT(*) FROM Aluno)
SET @VALOR = (SELECT TOP 1 MENSALIDADE FROM Aluno)
SET @VALOR_TURMA = (SELECT SUM(MENSALIDADE) FROM Aluno WHERE TURMA=@TURMA)

/*
if @TOTAL > 5
	BEGIN
		PRINT('Número de alunos MAIOR que 5')
		PRINT('O total de alunos é: ' + CONVERT(CHAR(10), @TOTAL))
	END

	ELSE
	BEGIN
		PRINT('Número de alunos MENOR que 5')
		PRINT('O total de alunos é: ' + CONVERT(CHAR(10), @TOTAL))
	END

*/

	IF @VALOR > 1000
	BEGIN
		DECLARE @PORCENTAGEM NUMERIC(6,2) 
		DECLARE @DESCONTO NUMERIC (6,2)

		SET @PORCENTAGEM = @VALOR * 0.10
		SET @DESCONTO = @VALOR -@PORCENTAGEM 
		PRINT ('O valor total de mensalidades é ' + CONVERT(CHAR(10), @VALOR))
		PRINT ('Desconto de 10% = ' + CONVERT(CHAR(10), @PORCENTAGEM))
	END

	ELSE
	BEGIN
		SET @PORCENTAGEM = @VALOR * 0.05
		SET @DESCONTO = @VALOR -@PORCENTAGEM 
		PRINT ('O valor total de mensalidades é ' + CONVERT(CHAR(10), @VALOR))
		PRINT ('Desconto de 5% =  ' + CONVERT(CHAR(10), @PORCENTAGEM))
		PRINT ('O valor a ser pago é: ' + CONVERT(CHAR(10), @DESCONTO))
	END
